name: Build

on:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - 'master'
  pull_request:
    paths-ignore:
      - '**.md' 

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: checkout
      uses: actions/checkout@v1

    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108 
        source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Setup nuget
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: 'latest'

    - name: Restore packages with nuget
      run: |
        msbuild ./PixelRPG.sln /restore /property:Configuration=Release
        msbuild ./PixelRPG.sln /restore /property:Configuration=Web

    - name: Build release with msbuild
      run: msbuild ./PixelRPG.PipelineImporter/PixelRPG.PipelineImporter.csproj /property:Configuration=Release

    - name: Build web with msbuild
      run: msbuild ./PixelRPG.sln /property:Configuration=Web

    - name: Push to gh-pages
      run: |
        git config --global user.email "autodeploy@noreply.github.com"
        git config --global user.name "Autodeploy"
        git checkout gh-pages
        git merge --no-ff --no-commit origin/master
        rm -recurse -force ./docs
        mkdir ./docs
        mv ./PixelRPG.Browser/bin/Web/net48/index.html ./docs/ -force
        mv ./PixelRPG.Browser/bin/Web/net48/web.config ./docs/ -force
        mv ./PixelRPG.Browser/bin/Web/net48/bridge ./docs/ -force
        mv ./PixelRPG.Browser/bin/Web/net48/Content ./docs/ -force
        ls ./docs
        git add --all .
        git status
        git commit -m "Merge master into gh-pages"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/ApmeM/PixelRPG.git          
        git push
